plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

author: Jing Tian Feng
title: Playground
tagline: Playground for Jekytrap
description: Playground for Jekytrap (Jekyll + Bootstrap 5 template)
url: https://jingtianfeng.github.io/jekytrap-playground/
logo: /assets/img/logo.png
