plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

author: (AUTHOR)
title: (TITLE)
tagline: (TAGLINE)
description: (DESCRIPTION)
url: (URL)
logo: /assets/img/logo.png
